googleapis/gax-php

src/AgentHeaderDescriptor.php, src/ApiCallable.php, src/CallSettings.php, tests/ApiCallableTest.php, tests/CallSettingsTest.php
- Move all descriptors from CallSettings to API level.
- Testing: unit tests
=> Implement custom GAPIC header in PHP.

src/FixedSizeCollection.php, src/Page.php, src/PageStreamingDescriptor.php, src/PagedListResponse.php, tests/ApiCallableTest.php, tests/FixedSizeCollectionTest.php, tests/PageTest.php, tests/mocks/MockRequest.php
Add support for pageSize parameter to getPage method in Page object, as required by FixedSizeCollection
Add requestPageSizeField support for PageStreamingDescriptor
=> Support pageSize parameter

composer.json
For reference: https://github.com/GoogleCloudPlatform/google-cloud-php/issues/255
=> upgrade auth

src/OperationResponse.php, tests/OperationResponseTest.php
=> Add OperationResponse getReturnTypeOptions

src/Testing/LongRunning/MockOperationsImpl.php
Required by https://github.com/googleapis/toolkit/pull/928 to test LRO methods
=> Add MockOperationsImpl

src/AgentHeaderDescriptor.php, tests/AgentHeaderDescriptorTest.php, tests/ApiCallableTest.php
Toolkit PR: https://github.com/googleapis/toolkit/pull/1042
=> Update agent header

src/ApiCallable.php, src/CallSettings.php, tests/ApiCallableTest.php
User headers are required for Spanner
cc @dwsupplee @jdpedrie
=> Add support for user headers

src/Testing/MockBidiStreamingCall.php, src/Testing/MockClientStreamingCall.php, src/Testing/MockStubTrait.php, tests/ApiCallableTest.php, tests/BidiStreamTest.php, tests/ClientStreamTest.php
Supports https://github.com/googleapis/toolkit/pull/1310
=> Update to allow access to call objects

src/AgentHeaderDescriptor.php
Depends on https://github.com/googleapis/gax-php/pull/74
=> Bump version to 0.10.0 for release

src/generated/Google/Longrunning/OperationsGrpcClient.php
Update longrunning grpc client with GPBEmpty
=> Update longrunning Grpc client

src/Serializer.php, tests/ApiExceptionTest.php
=> Update ApiException message to match REST format

composer.json
Context: https://github.com/GoogleCloudPlatform/google-cloud-php/pull/594
=> Relax auth requirements

.travis.yml, src/AgentHeaderDescriptor.php, src/ApiCallable.php, src/ApiException.php, src/BidiStream.php, src/CallHelperTrait.php, src/ClientStream.php, src/FixedSizeCollection.php, src/GrpcConstants.php, src/GrpcCredentialsHelper.php, src/OperationResponse.php, src/Page.php, src/PageStreamingDescriptor.php, src/PagedListResponse.php, src/Parser.php, src/PathTemplate.php, src/RetrySettings.php, src/Serializer.php, src/ServerStream.php
- Update docblocks on many public methods
- Add travis testing of PHP 7.0 and 7.1
- Small refactoring
=> Docs refactor

composer.json
cc @dwsupplee @jdpedrie @bshaffer @teboring
This is in response to https://github.com/google/protobuf/issues/3881
=> Pin protobuf version to 3.4

src/ApiCore/Parser.php, src/ApiCore/PathTemplate.php, tests/ApiCore/Tests/Unit/PathTemplateTest.php
Fixes https://github.com/googleapis/gax-php/issues/130
=> Fix poor errors from path template for empty input

src/ApiCore/AuthWrapper.php, src/ApiCore/Testing/MockGrpcTransport.php, src/ApiCore/Transport/GrpcTransport.php, src/ApiCore/Transport/RestTransport.php, src/ApiCore/TransportFactory.php, tests/ApiCore/Tests/Unit/Transport/GrpcTransportTest.php, tests/ApiCore/Tests/Unit/Transport/RestTransportTest.php
- Applies changes from https://github.com/googleapis/gax-php/pull/111 after merge of http transport PR.
- Mild refactoring to add AuthWrapper class
cc @pongad
=> Update auth handling

src/ApiCore/RequestBuilder.php
Fixes https://github.com/GoogleCloudPlatform/google-cloud-php/issues/957
=> calls local method for special class mappings instead of GPBUtil

src/ApiCore/AgentHeaderDescriptor.php
- Update version file handling to search below `src` directory (#179)
- Fix notice on missing fields, add debugging information (#178)
=> Prepare 0.33.0

composer.json
Pin to protobuf 3.5.* for patch release
=> Pin protobuf to 3.5.*

.travis.yml, ruleset.xml, src/ApiCore/Transport/TransportInterface.php, tests/ApiCore/Tests/Unit/Transport/GrpcTransportTest.php
Pulling these out of https://github.com/googleapis/gax-php/pull/182
=> Minor misc fixes

dev/sh/build-docs.sh, dev/src/Docs/SamiConfigBuilder.php
Remove proto files from doc generation since adding them to google-cloud-php. @dwsupplee @jdpedrie PTAL
=> Remove proto files from doc gen

src/ApiCore/ResourceTemplate/Parser.php, src/ApiCore/ResourceTemplate/RelativeResourceTemplate.php, src/ApiCore/ResourceTemplate/Segment.php, tests/ApiCore/Tests/Unit/PathTemplateTest.php, tests/ApiCore/Tests/Unit/ResourceTemplate/ParserTest.php
- Addresses changes flagged by @dwsupplee in his review of that PR
=> Follow up on Jison removal PR

dev/sh/build-docs.sh, src/ApiCore/ApiException.php, src/ApiCore/ArrayTrait.php, src/ApiCore/BidiStream.php, src/ApiCore/CredentialsWrapper.php, src/ApiCore/GapicClientTrait.php, src/ApiCore/Middleware/OperationsMiddleware.php, src/ApiCore/Middleware/ResponseMetadataMiddleware.php, src/ApiCore/Middleware/RetryMiddleware.php, src/ApiCore/OperationResponse.php, src/ApiCore/Page.php, src/ApiCore/PagedListResponse.php, src/ApiCore/RequestBuilder.php, src/ApiCore/Serializer.php, src/ApiCore/Testing/MessageAwareExporter.php, src/ApiCore/Testing/MockBidiStreamingCall.php, src/ApiCore/Testing/MockClientStreamingCall.php, src/ApiCore/Testing/MockGrpcTransport.php, src/ApiCore/Testing/MockServerStreamingCall.php, src/ApiCore/Testing/MockStubTrait.php, src/ApiCore/Testing/ProtobufGPBEmptyComparator.php, src/ApiCore/Testing/ProtobufMessageComparator.php, src/ApiCore/Testing/SerializationTrait.php, src/ApiCore/Transport/GrpcTransport.php, src/ApiCore/Transport/RestTransport.php, src/ApiCore/Transport/TransportInterface.php
- Mostly doc updates
- Minor changes to behaviour include exception transformation and type hints
=> Clean up warnings and docs

src/ApiCore/ResourceTemplate/AbsoluteResourceTemplate.php, src/ApiCore/ResourceTemplate/Parser.php, src/ApiCore/ResourceTemplate/RelativeResourceTemplate.php, src/ApiCore/ResourceTemplate/Segment.php, tests/ApiCore/Tests/Unit/PathTemplateTest.php, tests/ApiCore/Tests/Unit/ResourceTemplate/AbsoluteResourceTemplateTest.php, tests/ApiCore/Tests/Unit/ResourceTemplate/ParserTest.php, tests/ApiCore/Tests/Unit/ResourceTemplate/RelativeResourceTemplateTest.php
- Fixes #214
- Improves other messages
- Adds additional test cases
=> Improve path template error messages

src/Page.php, tests/Tests/Unit/PageTest.php
Required because of https://github.com/protocolbuffers/protobuf/issues/6195
=> Remove use of clone keyword

src/Version.php
Fixes #243. Ported from #244 for the 0.38 branch.
=> (pre-1.0) Add file exists check to gax readVersionFile method

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
Closes: https://github.com/googleapis/gax-php/issues/269
=> fix: accept a RetrySettings instance per call

src/CredentialsWrapper.php, src/GapicClientTrait.php, tests/Tests/Unit/CredentialsWrapperTest.php, tests/Tests/Unit/GapicClientTraitTest.php
Depends upon: https://github.com/googleapis/google-auth-library-php/pull/299
=> feat: add quota_project_id support

src/ResourceTemplate/Parser.php, tests/Tests/Unit/ResourceTemplate/ParserTest.php
=> fix: enable non-slash resource name seps [gax-php]

.gitattributes, .gitignore, .travis.yml, composer.json, dev/sh/build-docs.sh, dev/src/Docs/DoctumConfigBuilder.php, dev/src/Docs/doctum-config.php
Work done:
- Replaced Sami by [Doctum](https://github.com/code-lts/doctum#readme)
- Add a .gitattributes file to clean vendor tarball
I have some other @googleapis repos to do if this one is accepted: https://github.com/search?p=2&q=org%3Agoogleapis+sami&type=Code
=> chore: replace sami with doctum for doc generation

src/Transport/HttpUnaryTransportTrait.php, tests/Tests/Unit/Transport/RestTransportTest.php
=> fix: throws exceptions for unexpected header values

.gitattributes
Excludes unnecessary files from distribution. https://php.watch/articles/composer-gitattributes
If there are others, please let me know.
=> chore: exclude tests from distributed package

tests/Tests/Unit/GapicClientTraitTest.php
Add a test I neglected to add in #419.
=> chore: add test for interfaceOverride

.github/workflows/tests.yml, src/PollingTrait.php, tests/Tests/Unit/OperationResponseTest.php
=> fix: implicit conversion from float to int warning

src/ApiException.php, tests/Tests/Unit/ApiExceptionTest.php
Fix https://github.com/googleapis/gax-php/issues/446
=> fix: Fix default value for error message in createFromRequestException

.github/workflows/docs.yml
Remove read permission to fix docs generation
fixes https://github.com/googleapis/gax-php/issues/494
=> chore: fix docs generation

.github/workflows/release.yml, src/CredentialsWrapper.php
=> chore(ci): add workflow for running google/cloud tests before releases

src/Middleware/RetryMiddleware.php
addresses https://github.com/googleapis/gax-php/issues/504
=> fix: accept throwable for retry settings

src/GapicClientTrait.php
fixes https://github.com/googleapis/gax-php/issues/514
=> fix: ensure modifyClientOptions is called for new surface clients

tests/Tests/Unit/InsecureCredentialsWrapperTest.php
suggestion to add a test to #538
=> chore: add InsecureCredentialsWrapper test

src/InsecureCredentialsWrapper.php, src/Transport/HttpUnaryTransportTrait.php
Update InsecureCredentialsWrapper::getAuthorizationHeaderCallback to support grpc insecure channel.
=> fix: Update InsecureCredentialsWrapper::getAuthorizationHeaderCallback

composer.json
depends on https://github.com/GoogleCloudPlatform/grpc-gcp-php/pull/53
=> chore: add compatibility for Protobuf v4

src/CredentialsWrapper.php, tests/Tests/Unit/CredentialsWrapperTest.php
=> fix: Pass auth http handler to update metadata call

README.md, composer.json
This is a bit opinionated approach so feel free to close that proposal. 
From my experience simplifying the developer experience increases the number of valuable contributions.
I believe that exposing development tools through composer scripts makes devs' work easier since there is only one place they need to look to understand how to work with that repo.
=> chore: Improved developer experience by adding development commands to composer.json scripts

.github/workflows/docs.yml
should "fix" failing docs test in https://github.com/googleapis/gax-php/pull/582
=> fix(tests): skip docs tests from forks
