src/ApiCallable.php, tests/ApiCallableTest.php
Fix flaky test testRetryTimeoutExceeds using deterministic function to get elapsed time instead of relying on system clock.
=> Fix flaky test testRetryTimeoutExceeds

.travis.yml, src/AgentHeaderDescriptor.php, src/ApiCallable.php, tests/ApiCallableTest.php
Update the agent header to x-goog-api-client
Update the metadata processing so that x-goog-api-client is used (previously, "headers" was appearing in the metadata)
=> Update agent header

composer.json
@michaelbausor, we goofed on the auth fix earlier. The version should be `^0.11` to match [`google/apiclient`](https://github.com/google/google-api-php-client/blob/master/composer.json#L10), not `0.11`.
Can you merge and tag this as v0.4.1?
Thanks
=> Fix auth version constraint

.travis.yml, composer.json, ruleset.xml, src/Testing/MockStubTrait.php, src/Testing/MockUnaryCall.php, tests/ApiCallableTest.php, tests/BackoffSettingsTest.php, tests/CallSettingsTest.php, tests/FixedSizeCollectionTest.php, tests/GrpcCredentialsHelperTest.php, tests/Mocks/MockContent.php, tests/Mocks/MockCredentialsLoader.php, tests/Mocks/MockGrpcCredentialsHelper.php, tests/Mocks/MockRequest.php, tests/Mocks/MockResponse.php, tests/Mocks/MockStatus.php, tests/Mocks/MockStub.php, tests/OperationResponseTest.php, tests/PageStreamingDescriptorTest.php, tests/PageTest.php, tests/PagedListResponseTest.php, tests/PathTemplateTest.php, tests/bootstrap.php
Added namespaces to unit tests, which prompted much of the other changes.
=> Apply PSR2 formatting to all handwritten code

src/GrpcCredentialsHelper.php, tests/GrpcCredentialsHelperTest.php
Insecure credentials are represented as null, so we need to accept a null value. See https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/channel_credentials.c#L198
=> Handle insecure credentials

src/ApiException.php, src/GrpcConstants.php, src/Serializer.php, tests/ApiExceptionTest.php
An uncaught ApiException will now also display the metadata information, which can be critical to debugging.
=> Include metadata in ApiException toString method

composer.json, src/CallSettings.php
- Check retry_codes_name is set, otherwise can see undefined index errors when php.ini error reporting is set to strict
- Bump auth dependency to enable https://github.com/GoogleCloudPlatform/google-cloud-php/pull/535 (cc @bshaffer @jdpedrie @dwsupplee)
=> Check retry_codes_name, bump auth dependency

src/AgentHeaderDescriptor.php
Bumping from 0.10.0 to 0.20.0 to indicate the major nature of the change of protobuf implementations
=> Bump version to 0.20.0 for release

src/BidiStream.php, tests/ApiCallableTest.php, tests/BidiStreamTest.php, tests/ServerStreamTest.php
- Fix bidi resources streaming when repeated field methods return a RepeatedField object instead of an array
- Update tests for bidi and server streaming
=> Bidi streaming resources fix

src/Testing/MockStubTrait.php
Add array type declarations to match base class https://github.com/grpc/grpc/blob/master/src/php/lib/Grpc/BaseStub.php#L223, which is required by PHP 7
=> Add array types to MockStubTrait signature

.travis.yml, src/generated/Google/Logging/Type/LogSeverity.php, tests/InstantiateClassesTest.php
- Add a test that instantiates all of the generated protobuf classes in src/generated
- Rename instance of invalid DEFAULT keyword
=> Fix DEFAULT keyword in generated protobuf class

src/AgentHeaderDescriptor.php
=> Bump version to 0.22.1 for release

.travis.yml, tests/ProtobufExtensionTest.php
cc @dwsupplee @jdpedrie Once https://github.com/GoogleCloudPlatform/google-cloud-php/pull/600 is merged we should create a similar PR for google-cloud-php
Note that this doesn't test all combinations of platforms and c extension presence/absence - this is only to be a good citizen for Travis, as the extra testing combinations are (IMHO) unlikely to find issues.
=> Test protobuf c ext

src/CallSettings.php, src/Serializer.php
To support PHP5.5 prior 5.5.16, in which ucwords() does not have the second parameter.
=> Revert to using ucwords() without the delimiter parameter

composer.json, src/Testing/GeneratedTest.php, src/Testing/LongRunning/MockOperationsImpl.php, tests/AgentHeaderDescriptorTest.php, tests/ApiCallableTest.php, tests/ApiExceptionTest.php, tests/ApiStatusTest.php, tests/BidiStreamTest.php, tests/CallSettingsTest.php, tests/ClientStreamTest.php, tests/FixedSizeCollectionTest.php, tests/GrpcCredentialsHelperTest.php, tests/InstantiateClassesTest.php, tests/OperationResponseTest.php, tests/PageStreamingDescriptorTest.php, tests/PageTest.php, tests/PagedListResponseTest.php, tests/PathTemplateTest.php, tests/ProtobufExtensionTest.php, tests/RetrySettingsTest.php, tests/SerializerTest.php, tests/ServerStreamTest.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
Just needed to bump PHPUnit version to [`4.8.36`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4836---2017-06-21), to keep compatibility.
=> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

src/ApiCore/Jison/Parser.jison, src/ApiCore/Jison/Parser.php, src/ApiCore/Jison/Segment.php, src/ApiCore/PathTemplate.php, tests/ApiCore/Tests/Unit/PathTemplateTest.php, tests/ApiCore/Tests/Unit/RequestBuilderTest.php, tests/ApiCore/Tests/Unit/testdata/test_service_rest_client_config.php
We had some issues regarding the path template parser when colons were used in the URL for some actions. The issue was for URLs in the Spanner API like this:
```
/v1/projects/{name=projects/*/instances/*/operations/*}:cancel
```
The existing parser did not support this. To fix this, I added support for colons after wildcards. The updates in PathTemplate are a bit strange, but essentially the logic says "colons are allowed in wildcard names and also in path templates". The feature is URLs like this are supported. 
```
/v1/*:action
/v1/*:action/path
/v1/{name=*}:action
/v1/{name=*}:action/path
```
A potential negative is that for URLs *without* a colon, if the wildcard name was appended with a colon (in this case, ":cancel") the other URL would be used, e.g. `/v1/*` could potentially render …
=> adds support for :action in RequestBuilder

src/ApiCore/GapicClientTrait.php, tests/ApiCore/Tests/Unit/LongRunning/OperationsClientTest.php
This is a bugfix required for the [Spanner GAPIC](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Spanner/V1/SpannerClient.php#L50) to expose the transport implementation (used by the session pool to trigger asynchronous delete until official support is built in).
=> Move transport property from private to protected

src/ApiCore/GapicClientTrait.php
This allows a partial veneer to override these methods and modify the behaviour. For example, a partial veneer could override `setClientOptions` to set a default option, or `createCallStack` to insert a new piece of middleware.
=> Make gapic client trait methods protected

src/ApiCore/AgentHeaderDescriptor.php
This reverts commit 0da99ce6e3768e1e69401680cfb3906a2f254d92.
=> Revert "bump API Core version to 0.30.3 (#158)"

src/ApiCore/Middleware/RetryMiddleware.php
If a dependency throws a PHP7 Error instead of an Exception, this will make sure we bubble that up to our users.
=> Allow PHP7 errors to bubble up

.travis.yml, src/ApiCore/AuthWrapper.php, src/ApiCore/Transport/GrpcTransport.php
This updates the call_credentials_callback function to avoid needing `use ($authWrapper)`, which seems to have been triggering the segfaults.
=> Update auth wrapper to fix segfault

src/ApiCore/AuthWrapper.php, src/ApiCore/GapicClientTrait.php, src/ApiCore/Middleware/AuthWrapperMiddleware.php, src/ApiCore/Testing/MockGrpcTransport.php, src/ApiCore/Transport/GrpcTransport.php, src/ApiCore/Transport/RestTransport.php, src/ApiCore/TransportFactory.php, tests/ApiCore/Tests/Unit/GapicClientTraitTest.php, tests/ApiCore/Tests/Unit/LongRunning/OperationsClientTest.php, tests/ApiCore/Tests/Unit/Transport/GrpcTransportTest.php, tests/ApiCore/Tests/Unit/Transport/RestTransportTest.php
This possible change:
- Removes AuthWrapper from the transports, and makes it an option that can be passed to each call
- Adds middleware to inject an AuthWrapper from the client on each call (but as a side benefit, if the user passes one in it won't overwrite, so users can if they want specify an authWrapper per-call)
- Moves AuthWrapper build function into the AuthWrapper class
If we like the high-level idea here, we can then think about moving AuthWrapper out of gax and into the auth library itself. This change could also be cleaned up and submitted independently of the change to update constructor args.
=> Decouple auth and transport

src/ApiCore/ApiException.php, src/ApiCore/ApiStatus.php, src/ApiCore/Transport/RestTransport.php, tests/ApiCore/Tests/Unit/Transport/RestTransportTest.php
This ensures an `ApiException` is properly thrown *even if* the response returned is not in JSON format. For example, 404 messages are HTML.
Without this change, 404 errors generate the following (not helpful) error message: 
```
Google\ApiCore\Tests\Unit\Transport\RestTransportTest::testNonJsonResponseException
Undefined property: stdClass::$status
vendor/google/gax/src/ApiCore/Transport/RestTransport.php:164
vendor/google/gax/src/ApiCore/Transport/RestTransport.php:125
vendor/guzzlehttp/promises/src/RejectedPromise.php:40
vendor/guzzlehttp/promises/src/TaskQueue.php:47
vendor/guzzlehttp/promises/src/Promise.php:246
vendor/guzzlehttp/promises/src/Promise.php:223
vendor/guzzlehttp/promises/src/Promise.php:62
```
With this, the following error is returned:
```
Google\ApiCore\ApiException: …
```
=> Fixes REST ApiExceptions when result is not JSON

src/ApiCore/RequestBuilder.php, tests/ApiCore/Tests/Unit/RequestBuilderTest.php, tests/ApiCore/Tests/Unit/testdata/test_service_rest_client_config.php
Fix errors caused by default value of `placeholders` not being set before call to `buildBindings`
=> Fix Rest calls without placeholders

src/ApiCore/AgentHeaderDescriptor.php
Skipping 0.31.2 as that is already tagged: https://github.com/googleapis/gax-php/releases
Note that we are going to release from branch 0.31.x, which pulls in only #166 after 0.31.1
=> Bump version to 0.31.3 for release

src/ApiCore/Serializer.php
Currently, a PHP Notice accompanies the expected `\RuntimeException`. This change fixes the notice and adds a bit more debugging information to make it a bit easier to pinpoint which message is malformed.
=> Fix notice on missing field

src/ApiCore/AgentHeaderDescriptor.php
- Pin to protobuf version 3.5.* to avoid breakage caused by https://github.com/google/protobuf/issues/4738 (#184)
=> Prepare 0.33.1

src/ApiCore/AgentHeaderDescriptor.php
- Pin to protobuf version 3.5.* to avoid breakage caused by https://github.com/google/protobuf/issues/4738 (#184)
=> Prepare 0.32.1

composer.json, src/ApiCore/AgentHeaderDescriptor.php
- Pin to protobuf version 3.5.* to avoid breakage caused by https://github.com/google/protobuf/issues/4738 (#184)
=> Prepare v0.30.3

src/ApiCore/AgentHeaderDescriptor.php
- Pin to protobuf version 3.5.* to avoid breakage caused by https://github.com/google/protobuf/issues/4738 (#188)
=> Prepare 0.29.1

src/ApiCore/GapicClientTrait.php, tests/ApiCore/Tests/Unit/GapicClientTraitTest.php
Make CredentialsWrapper protected in GapicClientTrait. We have received a request to make this available from other teams using the generated clients.
=> Make CredentialsWrapper protected

src/ApiCore/ApiException.php, src/ApiCore/Transport/GuzzleTransportTrait.php, src/ApiCore/Transport/HttpUnaryTransportTrait.php, src/ApiCore/Transport/RestTransport.php
This PR is intended to prepare the ground for adding support for the grpc-fallback transport (serial protobuf over HTTP 1.1). It:
- Adds ApiException::createFromRpcStatus
- Refactors functionality from RestTransport into GuzzleTransportTrait
- No behaviour changes
=> Preparatory refactoring to add grpc-fallback support

src/ApiCore/CredentialsWrapper.php, src/ApiCore/GapicClientTrait.php, src/ApiCore/Transport/HttpUnaryTransportTrait.php, tests/ApiCore/Tests/Unit/CredentialsWrapperTest.php
Handle and test for empty or null access tokens, which may be returned by insecure/anonymous credentials.
=> Support empty or null access tokens

src/ApiCore/RetrySettings.php
In accordance with https://github.com/GoogleCloudPlatform/google-cloud-php/pull/1311
=> Cover org rename: googlecloudplatform -> googleapis

src/PagedListResponse.php, tests/Tests/Unit/PagedListResponseTest.php
PTAL, and let me know whether we need more or clearer documentation. cc @sirtorry, @tmatsuo 
Closes #153
=> Make PagedListResponse iterable

src/Transport/Grpc/UnaryInterceptorInterface.php, src/Transport/GrpcTransport.php, tests/Tests/Unit/Transport/GrpcTransportTest.php
- Adds a deserialize argument to the UnaryInterceptorInterface::interceptUnaryUnary method to match the grpc interface: https://github.com/grpc/grpc/blob/master/src/php/lib/Grpc/Interceptor.php#L30
- Adds a test for the interceptor
cc @fiboknacky
=> Update interceptor interface to match grpc

src/Call.php, src/Page.php, src/RequestBuilder.php, src/UriTrait.php
WIP PR to add internal tags and remove references in Call to protobuf Message class, PTAL.
=> Add internal tags, remove Message from Call

.travis.yml, composer.json
Addresses: https://github.com/googleapis/google-cloud-php/issues/1805
This should be reverted once we have protobuf v3.7.1 available on app engine.
=> Loosen conflict to protobuf v3.7.0

src/RequestBuilder.php, tests/Tests/Unit/RequestBuilderTest.php, tests/Tests/Unit/testdata/test_service_rest_client_config.php
A request with an empty Message object is being JSON encoded as an array `[]` instead of object `{}`. For instance, this request:
```php
$message = new MockRequestBody();
$message->setName('message/foo');
$anotherMessage = new MockRequestBody();
$message->setNestedMessage($anotherMessage);
```
will output this:
```json
{"name":"message\/foo","nestedMessage":[]}
```
when it should output this:
```json
{"name":"message\/foo","nestedMessage":{}}
```
This fix will work when `body = *` in the rest client config, but will not work if the `body` is a property of the message.
**EDIT**: Added fix so it works when body is a property of the message
=> Fix JSON empty object encoding

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
Disables resolution of the gRPC ServiceConfig from DNS TXT Records. Context https://github.com/googleapis/gapic-generator/issues/2778.
=> Disable service config resolution by default

src/Version.php
Fixes #243.
The existing method suppresses error output, but if a custom error handler is enabled, it will catch the warning. This change adds a `file_exists()` check to prevent attempting to read a non-existent file.
=> Add file exists check to gax readVersionFile method

.travis.yml, src/RequestParamsHeaderDescriptor.php, tests/Tests/Unit/RequestParamsHeaderDescriptorTest.php
Fixes https://github.com/googleapis/google-cloud-php/issues/2297.
=> fix: Properly format grpc metadata keys for non-ASCII values

composer.json, src/Transport/Grpc/UnaryInterceptorInterface.php, src/Transport/GrpcTransport.php, tests/Tests/Unit/Transport/GrpcTransportTest.php
This change exposes straight forward support for [gRPC's Interceptors](https://github.com/grpc/grpc-php/blob/832c9c5/src/lib/Interceptor.php) (which adds the ability to add interceptors on streaming calls) while continuing to support the now deprecated `UnaryInterceptorInterface`.
A quick example:
```php
use Google\ApiCore\Transport\GrpcTransport;
use Grpc\Interceptor;
$transport = GrpcTransport::build('my-endpoint:443', [
'interceptors' => [new PrintMethodInterceptor()]
]);
```
```php
class PrintMethodInterceptor extends Interceptor
{
public function interceptUnaryUnary(
$method,
$argument,
$deserialize,
array $metadata = [],
array $options = [],
$continuation
) {
print("Intercepted unary call to: $method" . PHP_EOL);
return $continuation($method, $argument, $deserialize, $metadata, …
```
=> feat: Deprecate ApiCore interceptor support in favor of gRPC implementation

src/Transport/RestTransport.php
This flag will ensure we don't throw exceptions with the rest transport when dealing with unknown enum fields. Please see https://github.com/protocolbuffers/protobuf/pull/7455/files for the protobuf implementation.
=> feat: ignore unknown fields by default

tests/Tests/Unit/PageStreamingDescriptorTest.php, tests/Tests/Unit/ResourceTemplate/AbsoluteResourceTemplateTest.php, tests/Tests/Unit/ResourceTemplate/ParserTest.php, tests/Tests/Unit/ResourceTemplate/RelativeResourceTemplateTest.php, tests/Tests/Unit/Transport/Grpc/ForwardingServerStreamCallTest.php
Follows up on https://github.com/googleapis/gax-php/pull/278 addressing concerns as a result of running `composer install --optimize-autoloader`.
=> tests: namespace fixes

src/CredentialsWrapper.php, src/GapicClientTrait.php, src/Transport/GrpcTransport.php, src/Transport/HttpUnaryTransportTrait.php, tests/Tests/Unit/CredentialsWrapperTest.php, tests/Tests/Unit/GapicClientTraitTest.php, tests/Tests/Unit/Transport/GrpcTransportTest.php, tests/Tests/Unit/Transport/RestTransportTest.php
This PR implements changes to allow the GAPIC clients to default to self-signed JWTs by doing the following:
1. Adds `defaultScopes` option for GAPIC clients
1. Uses `updateMetadata` instead of `fetchAuthToken` in `CredentialsWrapper` in order to take advantage of the self-signed JWT logic in `google/auth`
1. When the `SERVICE_ADDRESS` constant is defined, the Gapic clients pass this through the auth library as the `$authUri` when fetching an access token.
1. Calls `getAuthorizationHeaderCallback` in `RestTransport` for consistency
1. Deprecates `getBearerString` in favor of `getAuthorizationHeaderCallback`
No behavior should be impacted until we roll out `defaultScope` config values in Gapic clients.
**Important**
Depends on https://github.com/googleapis/google-auth-library-php/pull/306 …
=> feat: default to self-signed JWTs and use updateMetadata for fetching tokens

src/CredentialsWrapper.php, src/Transport/HttpUnaryTransportTrait.php, tests/Tests/Unit/Transport/RestTransportTest.php
gRPC already passes an argument to the credentials callback, and it's a stdObj with `service_url` and `method_name` properties. So we cannot use this parameter, and we don't need to.
=> fix: Do not pass headers to credentials callback

.github/CODEOWNERS
Narrows down CODEOWNER `actools` to `actools-php`.
=> chore: codeowners replace actools w/actools-php

.github/workflows/docs.yml, dev/sh/build-docs.sh
- More accurate comments
- Removes codepaths for when arguments are not present, which no longer exist
- Misc refactor
=> chore: cleanup build-docs script

src/GapicClientTrait.php
Alias the "validate" function in `GapicClientTrait` to prevent conflict with generated validate method. This prevents errors for generated GAPIC clients which contain a `validate` method.
Here is an example of what this is meant to address from the upcoming Compute GAPIC:
```php
class UrlMapsGapicClient
{
use GapicClientTrait;
//...
public function validate($project, $urlMap, array $optionalArgs = [])
{
$request = new ValidateUrlMapRequest();
$request->setProject($project);
$request->setUrlMap($urlMap);
if (isset($optionalArgs['urlMapsValidateRequestResource'])) {
$request->setUrlMapsValidateRequestResource($optionalArgs['urlMapsValidateRequestResource']);
}
return $this->startCall(
'Validate',
UrlMapsValidateResponse::class,
$optionalArgs,
$request
)->wait();
}
}
```
=> fix: alias "validate" in GapicClientTrait 

src/Middleware/RetryMiddleware.php
https://github.com/googleapis/gax-java/issues/591 states that _not_ imposing attempt delay when retrying a timed out RPC could worsen overload outages, a common source of client timeout issues. The relevant code was removed in https://github.com/googleapis/gax-java/pull/597.
I found that similar code existed in gax-php, and with no other language doing something similar still that I could find, I figured it should be removed.
=> fix: remove handling of deadline_exceeded delay

src/AgentHeader.php, src/GapicClientTrait.php, tests/Tests/Unit/AgentHeaderTest.php, tests/Tests/Unit/GapicClientTraitTest.php
This is needed primarily for REGAPIC. However, sending the REST header can also benefit gRPC and REST GAPIC libraries (the default) as well, since we don't support gRPC-only libraries.
Using gax-php's version as the default REST version.
=> [gax-php] feat: add REST headers

src/RetrySettings.php, tests/Tests/Unit/Middleware/RetryMiddlewareTest.php, tests/Tests/Unit/RetrySettingsTest.php
This PR adds a helper to the `RetrySettings` for configuring a logical call timeout. This helper, `logicalTimeout`, takes a single integer and applies it to each of the four existing timeout settings and sets the timeout multiplier to 1, returning an associative array for use with `with()` or via the `retrySettings` call option. The result is that each RPC attempt will take no longer than the time remaining in the overall deadline calculated at the start of the first call using the given timeout. The time remaining in this overall deadline is the timeout for each RPC attempt.
This helper is meant to simplify how users can think about the timeout settings, and reduce the need for `DEADLINE_EXCEEDED` to be retryable, which is an anti-pattern, but necessary for the "timeout backoff" strategy …
=> feat: add logical timeout helper to RetrySettings

src/RequestBuilder.php, tests/Tests/Unit/RequestBuilderTest.php, tests/Tests/Unit/testdata/test_service_rest_client_config.php
Follows https://github.com/googleapis/gapic-generator-php/commit/2d5ef5853544d58de2b6fdd5cb8335c38174af23
=> fix: ensure required query parameters with default values get sent over the wire

composer.json, src/CredentialsWrapper.php, src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
**TODO** 
_Note_: These steps are now optional because Compute does not need the exclusion for Self-Signed JWTs with Scopes
=> feat: allow ServiceAccountJwtAccessCredentials to sign scopes

src/Testing/GeneratedTest.php, tests/Tests/Unit/AgentHeaderTest.php, tests/Tests/Unit/GapicClientTraitTest.php, tests/Tests/Unit/LongRunning/OperationsClientTest.php, tests/Tests/Unit/Middleware/RetryMiddlewareTest.php, tests/Tests/Unit/OperationResponseTest.php, tests/Tests/Unit/RequestBuilderTest.php, tests/Tests/Unit/Transport/Rest/JsonStreamDecoderTest.php
This PR ensure that :
- stricter assertions are used for string comparisons (`assertEquals` -> `assertSame`)
- `assertCount` and `assertTrue` dedicated assertions are used when they should
=> chore: tests assertions

composer.json
Update to allow for `google/common-protos 2.0`. We are keeping `google/common-protos 1.0` for backwards-compatibility purposes.
=> chore: allow for google/common-protos 2.0

src/Testing/MockServerStreamingCall.php
Tests in `google/cloud` are failing with the following error:
```
1) Google\Cloud\BigQuery\Storage\Tests\Unit\V1\BigQueryReadClientTest::readRowsExceptionTest
Undefined property: stdClass::$metadata
/tmpfs/src/github/google-cloud-php/vendor/google/gax/src/Testing/MockServerStreamingCall.php:93
/tmpfs/src/github/google-cloud-php/vendor/google/gax/src/ServerStream.php:79
/tmpfs/src/github/google-cloud-php/BigQueryStorage/tests/Unit/V1/BigQueryReadClientTest.php:211
```
This should fix it!
=> fix: support stdClass in MockServerStreamingCall

src/ServerStream.php, src/ServerStreamingCallInterface.php, src/Testing/MockServerStreamingCall.php, src/Transport/Grpc/ServerStreamingCallWrapper.php, src/Transport/Rest/RestServerStreamingCall.php
This reverts the changes to the `getStatus` API of the server streaming calls that made it return `google.rpc.Status` rather than `stdClass`.  The REST flavor of ServerStream will throw an exception prior to `getStatus` calls, so that API is essentially not used in REST, so we shouldn't have changed the return type to something transport agnostic. This was also an accidental breaking change, even though the changes were to an internal interface/call stack.
Fixes #363, tested with the repro mentioned there.
=> fix: revert getStatus to stdClass in ServerStreamingCallInterface

.github/workflows/docs.yml
Our docs haven't published since `v1.6.1` because the ubuntu version we were using was deprecated.
Also, if we add `workflow_dispatch` we can run the documentation from the Actions UI
=> chore: fix docs workflow and add workflow_dispatch

.github/sync-repo-settings.yaml, .github/workflows/tests.yml, README.md, composer.json
Related to https://github.com/googleapis/gax-php/pull/389
Drop support for PHP 5.5 to make testing easier, and because it's really old
PHP Support across PHP libraries as of this moment:
- `google/gax` (this library): PHP 5.5
- `google/cloud`: PHP 5.5 (with the exception of Compute and SqlAdmin)
- `google/apiclient`: PHP 5.6
- `google/auth`: PHP 7.1
=> chore: remove PHP 5.5 support

.github/workflows/docs.yml, dev/sh/build-docs.sh
Fixes docs generation by 
- allowing for "v" in tags when matching the contents of the `VERSION` file (we switched to adding `v` before the release number at around `v1.7.0` to be consistent with the other libraries)
- ensure the PHP version is consistent (and update it to 7.4)
=> chore: fix docs generation

composer.json, dev/sh/build-docs.sh, src/BidiStream.php, src/Testing/MockStubTrait.php, tests/Tests/Unit/GrpcSupportTraitTest.php, tests/Tests/Unit/Transport/GrpcTransportTest.php
- Update doctum version for PHP 8.1 in #409 
- fix skipped PHP tests
- fix misc type-hinting issues from `google/cloud` tests
- updates minimum common protos version
=> chore: update doctum, fix phpunit warnings, fix misc typehinting

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
This just applies to `startApiCall` which is not in use anywhere yet.
=> fix: use responseType for custom operations

composer.json
The latest versions of `phpunit` require `phpspec/prophecy` as a separate package
=> chore: add phpspec prophecy to require-dev

src/CredentialsWrapper.php, tests/Tests/Unit/CredentialsWrapperTest.php, tests/Tests/Unit/OperationResponseTest.php
Similar to [NodeJS's eager threshold](https://github.com/googleapis/google-auth-library-nodejs/blob/883cf2596664b7de8159fb29a8f16705218a2ad4/src/auth/jwtaccess.ts#L108), add an eager threshold in order to refresh tokens a little bit early and prevent issues judged by clocks being slightly off, or race conditions.
=> fix: add eager threshold

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
We will start generating the an `interfaceOverride` descriptor config as part of https://github.com/googleapis/gapic-generator-php/pull/510 which will take the place of the `interfaceName` parameter on `startApiCall`. This will allow `sendAsync`/`startAsynCall` to also exclude the `interfaceName`, a param the user should not have to set.
Doing this change now with `startApiCall` allows for a patch release which we can then use for testing https://github.com/googleapis/gapic-generator-php/pull/510 in.
=> fix: use interfaceOverride instead of param

dev/sh/build-docs.sh
Without this, the "view source" link on any docs page with the tag name starting with `v` (so, all of our most recent tags) results in a 404.
For example, see https://googleapis.github.io/gax-php/1.17.0/Google/ApiCore/AgentHeader.html
=> chore(docs): preserve exact tag name for correct links

dev/sh/build-protobuf-docs.sh
Fix issue where user supplied tag can be a mismatch from the actual protobuf version (see cl/496981224)
=> chore(docs): ensure generated protobuf docs uses supplied version

src/GapicClientTrait.php, src/Transport/RestTransport.php, tests/Tests/Unit/GapicClientTraitTest.php, tests/Tests/Unit/Transport/RestTransportTest.php
There are a few rare cases where metadata return types for long running operations aren't being added into the descriptor pool when utilizing the REST transport. This fix ensures they are added by instantiating the metadata class, which triggers an `initOnce`call which loads the data into the associated pool.
=> fix: ensure metadata return type is loaded into descriptor pool

composer.json, src/CredentialsWrapper.php, tests/Tests/Unit/CredentialsWrapperTest.php
Will require an update to the minimum `google/auth` version once https://github.com/googleapis/google-auth-library-php/pull/431 is merged
**Note**: We will also need to cherry-pick this commit into [v1.19.0](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.19.0) and tag `v1.19.1` as well, in order to maintain compatibility in PHP 7.0.
=> fix: ensure cache is used in calls to ADC::onGCE

.github/workflows/docs.yml, .github/workflows/tests.yml
Following up on Step Security's suggestions to restrict permissions for `GITHUB_TOKEN`.
=> chore: github workflows marked readOnly

src/Middleware/RetryMiddleware.php, tests/Tests/Unit/Middleware/RetryMiddlewareTest.php
RetrySettings/RetryMiddleware supports a totalTimeoutMs option which caps the overall timeout for all retries. At the moment, when this is active it can result in RetryMiddleware calculating that the timeout for the next call should be a floating point value.
This is because the calculation includes the current time found by `microtime(true) * 1000`, which returns a floating point value.
When used in combination with the GRPC transport, the timeout value will eventually end up in \Grpc\AbstractCall::__construct(). That class checks that the value passes `is_numeric()` and then attempts to create `\Grpc\Timeval($timeout)`. However that class is typed to take an integer, and so PHP >= 8.1 gives a deprecation error like:
```
Implicit conversion from float 9999998.046875 to int loses …
```
=> fix: ensure timeout set by RetryMiddleware is int not float

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
Reverts googleapis/gax-php#313
This seems a necessary piece of code as this was responsible for forwarding the default auth scopes of the clients using [GapicClientTrait](https://github.com/googleapis/gax-php/blob/main/src/GapicClientTrait.php).
We started receiving errors related to missing auth. More info at this [issue](https://github.com/googleapis/google-cloud-php/issues/6386).
=> Revert "chore: remove unnecessary api endpoint check"

src/GapicClientTrait.php
Fix for the following deprecation notice:
```
PHP Deprecated:  Creation of dynamic property Google\Cloud\PubSub\V1\PublisherClient::$newClient 
is deprecated in /Users/vishwarajanand/github/google-cloud-php/PubSub/vendor/google/gax/src/GapicClientTrait.php 
on line 1077
```
=> fix: deprecation notice while GapicClientTrait->setClientOptions

.github/workflows/docs.yml
The docs generation job is failing, and I believe this is because we are using  a non-existent `secrets.ACCESS_TOKEN` instead of the default `secrets.GITHUB_TOKEN`
see https://docs.github.com/en/actions/security-guides/automatic-token-authentication
I'm not sure what caused this to start failing - I may have removed the secret because I thought it was unused
=> chore(docs): update token name

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
Now that we've merged https://github.com/googleapis/gapic-generator-php/pull/659, this needs to be released before we update the clients in `google-cloud-php`, to ensure GAPIC library tracking continues to function.
=> feat: ensure NewClientSurface works for consoldiated v2 clients

src/CredentialsWrapper.php
Follow up to https://github.com/googleapis/gax-php/pull/452 - we need to make the `$credentialsFetcher` property of `CredentialsWrapper` nullable, otherwise tests in the monorepo will fail
=> fix: ensure credentialsFetcher is nullable

src/GapicClientTrait.php, src/Middleware/CredentialsWrapperMiddleware.php, src/Middleware/FixedHeaderMiddleware.php, src/Middleware/MiddlewareInterface.php, src/Middleware/OperationsMiddleware.php, src/Middleware/OptionsFilterMiddleware.php, src/Middleware/PagedMiddleware.php, src/Middleware/ResponseMetadataMiddleware.php, src/Middleware/RetryMiddleware.php, tests/Tests/Unit/GapicClientTraitTest.php
Implementation for Option 2 of [go/php-interceptors-and-middlewares](https://goto.google.com/php-interceptors-and-middlewares):
```php
$client->addMiddleware(function (MiddlewareInterface $handler) {
return new class ($handler) implements MiddlewareInterface {
public function __construct(private MiddlewareInterface $handler) {
}
/**
* Modify or observe the API call request and response.
* The returned value must include the result of the next MiddlewareInterface invocation in the
* chain.
*
* @param Call $call
* @param array $options
* @return PromiseInterface|ClientStream|ServerStream|BidiStream
*/
public function __invoke(Call $call, array $options) {
// do middleware stuff (pre-request)
$response = ($this->handler)($call, $options);
// do middleware stuff (post-request)
return …
```
=> feat: interface and methods for middleware stack

phpunit.xml.dist, tests/Tests/Unit/GapicClientTraitTest.php, tests/Tests/Unit/Transport/GrpcTransportTest.php
Fixing following warnings:
1. GrpcTransportTest
```
PHP Deprecated: Creation of dynamic property Google\ApiCore\Tests\Unit\Transport\MockCallInvoker::$mockCall is deprecated in /usr/local/google/home/vishwarajanand/github/gax-php/tests/Tests/Unit/Transport/GrpcTransportTest.php on line 589
```
2. GapicClientTraitTest
```PHP Deprecated:  Creation of dynamic property Google\ApiCore\Middleware\MiddlewareInterface@anonymous::$handler is deprecated in /usr/local/google/home/vishwarajanand/github/gax-php/tests/Tests/Unit/GapicClientTraitTest.php on line 1760
PHP Deprecated:  Creation of dynamic property Google\ApiCore\Middleware\MiddlewareInterface@anonymous::$m2Called is deprecated in /usr/local/google/home/vishwarajanand/github/gax-php/tests/Tests/Unit/GapicClientTraitTest.php on line 1761 …
```
=> chore: gax test warnings

composer.json
we need to use `~2.0` instead of `^2.0`  for `google/longrunning` in order to allow version `0.3` (and future `0.x` releases). This is because, as the library is part of `google/cloud`, when a new feature release rolls out, it breaks the build because it cannot find a suitable version (see https://github.com/googleapis/google-cloud-php/pull/6868)
=> fix: widen google/longrunning version

src/Transport/RestTransport.php
fixes https://github.com/googleapis/gax-php/issues/310
Properly accepts all `Throwable` types in Guzzle promises
See https://github.com/guzzle/promises/blob/2.0/src/RejectedPromise.php#L52
=> fix: correct exception type for Guzzle promise

src/ArrayTrait.php, tests/Tests/Unit/ArrayTraitTest.php
The purpose of this PR is to make ArrayTrait in ApiCore consistent with the ArrayTrait in Core.
With this we can replace the references of Core/ArrayTrait with ApiCore/ArrayTrait in v2 handwritten clients.
=> feat: update ArrayTrait to be consistent with Core

src/CredentialsWrapper.php, src/Transport/GrpcTransport.php, tests/Tests/Unit/Transport/GrpcTransportTest.php
fixes #533
Checks the universe domain _before_ invoking the grpc libraries. This ensures that a segfault doesn't happen when the universe domain is invalid. 
1. Is this the best way to do this?
2. Should this be addressed in grpc core itself?
=> fix: universe domain check for grpc transport

src/CredentialsWrapper.php, tests/Tests/Unit/CredentialsWrapperTest.php
Currently the [v2 samples for Pubsub](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1967) are failing due to an internal attempt to `serialize` the `PubSubClient` in the `BatchPublisher`.
This is because the default `authHttpHandler` contains a closure. With this PR we make the default handler as `null`.
=> feat: Make the default authHttpHandler in CredentialsWrapper null

.github/workflows/tests.yml, src/Serializer.php
The 2 major changes here are:
For a simple script that calls `Select * From <table> LIMIT 100` where the table has 23 columns, the `getGetter` and `toCamelCase` were being called close to 500 times. Even though the operation is simple, but there is string manipulation and depends on the names that are used frequently. So, I simply added some caching for these methods.
The `getDescriptorMaps` depends on the `$messageType` which stays same inside the `for loop`. Moreover, the first argument returned, is actually a list of fields. So, instead of depending on the `$fieldsCount`, we can use this list to loop over the `$fields`.
I ran a simple script that runs the same query as above 5 times, both with and without the protobuf extension enabled and I could see a good improvement for both the …
=> chore: Add caching and micro optimizations in Serializer.

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
This adds the API version header to the `GapicClientTrait` trait for the new api version control.
=> feat: Add the api header to the GapicClientTrait

.github/workflows/tests.yml, README.md, phpunit.xml.dist
The solution mentioned [here](https://github.com/googleapis/gax-php/pull/555#discussion_r1575000105) is already implemented, when I first time tried to execute those tests they were failing not due to missing extensions, but missing env var. 
I moved that env var to phpunit.xml.dist so now the whole testsuite should pass regardless if the extensions are installed or not.
=> fix: failing tests by moving GOOGLE_APPLICATION_CREDENTIALS to phpunit.xml.dist

.github/workflows/tests.yml, composer.json
For those folks that would like to run phpstan before they open a PR I moved phpstan to lib dev dependencies as it's not creating any conflicts.
=> chore(tests): add phpstan as a dev dependency

src/CredentialsWrapper.php, tests/Tests/Unit/CredentialsWrapperTest.php
=> chore: disable universe domain check for MDS

.repo-metadata.json, README.md, src/Options/CallOptions.php, src/Options/ClientOptions.php
misc fixes that will allow  googleapis/google-cloud-php#7797 to pass
- Adds `.repo-metadata.json` to this repo
- fixes "broken references"
- updates outdated PHP version in README
=> chore: misc fixes to allow for docs generation

src/GapicClientTrait.php, tests/Tests/Unit/GapicClientTraitTest.php
fixes bad edit made in  https://github.com/googleapis/gax-php/commit/8d03965a341a481f57cd33abe42eefaddb245d4e#r148984939 as part of https://github.com/googleapis/gax-php/pull/582
alternative implementation of https://github.com/googleapis/gax-php/pull/593, but does not add `hasEmulator` to `ClientOptions` (because we don't want to expose `hasEmulator` as a client option)
=> fix: ensure hasEmulator client option is passed to createTransport

.github/sync-repo-settings.yaml, .github/workflows/tests.yml, README.md, composer.json
Reverts googleapis/gax-php#598, we will drop PHP 8.0 next year
See https://github.com/googleapis/google-auth-library-php/pull/594
=> Revert "chore: drop support for PHP 8.0"

.github/workflows/tests.yml, src/ApiException.php, src/Call.php, src/CredentialsWrapper.php, src/GapicClientTrait.php, src/Page.php, src/PathTemplate.php, src/RequestBuilder.php, src/ResourceHelperTrait.php, src/ResourceTemplate/Parser.php, src/ResourceTemplate/RelativeResourceTemplate.php, src/ResourceTemplate/Segment.php, src/Testing/MockBidiStreamingCall.php, src/Testing/MockClientStreamingCall.php, src/Testing/MockServerStreamingCall.php, src/Testing/MockStatus.php, src/Testing/MockStubTrait.php, src/Testing/MockUnaryCall.php, src/Transport/GrpcTransport.php
Ensures that the last GAX release which is compatible with PHP 7.4 will be compatible with PHP 8.4 as well.
Once this is merged, we will tag this as `v1.29.2`
fixes https://github.com/googleapis/gax-php/issues/596
=> fix: add PHP 8.4 compatibility to last release compatible with PHP 7.4

composer.json
Should happen before https://github.com/googleapis/google-cloud-php/pull/8519
=> chore: drop protobuf 3.x runtime and extension

src/OperationResponse.php, tests/Unit/OperationResponseTest.php, tests/Unit/testdata/src/CustomOperationClient.php
fixes https://github.com/googleapis/gax-php/issues/565
=> fix: ensure compute request build parameters have the operation ID last

src/OperationResponse.php, src/ServerStream.php
required for https://github.com/googleapis/gapic-generator-php/pull/767
ensures that PHPStan understands the "generic" syntax used in the GAPIC generator for LROs
=> docs: add template for operation result
